# Generated by Django 3.1.1 on 2020-11-21 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_auto_20201106_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='pub_date',
        ),
    ]
