# Generated by Django 3.1.1 on 2020-11-25 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_remove_playlist_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='playlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='playlist.playlist'),
        ),
    ]
