# Generated by Django 3.1.1 on 2020-11-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0005_auto_20201127_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='url',
            field=models.FileField(blank=True, null=True, upload_to='playlist/music'),
        ),
    ]
